### ISSUE TITLE
Memory management of a frame once enqueued

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-insertable-streams#5]
Similarly to https://github.com/w3c/webrtc-insertable-streams/issues/49, it would be interesting to optimise the memory model of this API.
When JS receives a raw frame, it is convenient to have access to the frame pixels.
After JS enqueues the frame, the enqueued frame may be used for other purposes (some other JS processing for instance).
It might be best to detach at least the pixel data of the frame once processing is done (i.e. frame is enqueued).

**Comment by aboba** [comment]
Question: can the "memory" be a GPU buffer?  It would be desirable to be able to avoid uploading/downloading between GPU and main memory.

**Comment by alvestrand** [comment]
yes, the enqueue operation seems to be intended to release the frame from JS control. This should be documented.

**Comment by guidou** [comment]
The spec now explicitly says that the close() method of the VideoFrame must be called when a frame is written to the writable.
I think this addresses this issue, but please reopen if necessary.
